/**
 * People display-name aliases — keep prior names searchable after a rename.
 * The current `people.name` is the only display name.
 */

const AUTO_LABEL = /^Person\s+\d+$/i;
const MAX_ALIASES = 20;

export function isAutoGeneratedPersonName(name: string): boolean {
  const trimmed = name.trim();
  return !trimmed || AUTO_LABEL.test(trimmed);
}

export function normalizePersonNameKey(name: string): string {
  return name.trim().replace(/\s+/g, " ").toLowerCase();
}

export function namesEqual(a: string, b: string): boolean {
  return normalizePersonNameKey(a) === normalizePersonNameKey(b);
}

export function normalizeNameAliases(aliases: unknown): string[] {
  if (!Array.isArray(aliases)) return [];
  const seen = new Set<string>();
  const out: string[] = [];
  for (const raw of aliases) {
    if (typeof raw !== "string") continue;
    const trimmed = raw.trim().replace(/\s+/g, " ");
    if (!trimmed || isAutoGeneratedPersonName(trimmed)) continue;
    const key = normalizePersonNameKey(trimmed);
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(trimmed);
    if (out.length >= MAX_ALIASES) break;
  }
  return out;
}

/**
 * After a rename, keep the previous display name as an alias so
 * “photos of Craig Hale” still matches after rename to “Craig”.
 * The new name is never stored as an alias.
 */
export function mergePersonNameAlias(input: {
  currentName: string;
  nextName: string;
  aliases: unknown;
}): string[] {
  const current = input.currentName.trim().replace(/\s+/g, " ");
  const next = input.nextName.trim().replace(/\s+/g, " ");
  const aliases = normalizeNameAliases(input.aliases).filter(
    (alias) => !namesEqual(alias, next),
  );
  if (!current || namesEqual(current, next) || isAutoGeneratedPersonName(current)) {
    return aliases;
  }
  if (aliases.some((alias) => namesEqual(alias, current))) {
    return aliases;
  }
  return [current, ...aliases].slice(0, MAX_ALIASES);
}
