/**
 * Will Planner — legal disclaimer constants (client-safe).
 */

/** Bump when disclaimer text changes; forces re-acceptance. */
export const WILL_DISCLAIMER_VERSION = "will_disclaimer_v1";

/**
 * Required on every screen, PDF/DOCX, and download email footer.
 * Do not paraphrase in user-facing CTAs or generated drafts.
 */
export const WILL_DISCLAIMER_TEXT =
  "This is a planning draft generated by Family Memory Vault. It is not a will, trust, or legal advice. It is not valid until an attorney licensed in your state reviews it and you sign it with the witnesses/notary your state requires.";

/** Short label for banners / form titles. */
export const WILL_DISCLAIMER_TITLE = "Planning draft — not a legal will";
