/**
 * Common object / scene vocabulary for Ask AI disambiguation.
 * Tokens here must never be treated as People-list names.
 */

import { listVisualSynonymKeys } from "@/lib/ai/visual-search";

/** Household, events, places, clothing, animals, vehicles, food, etc. */
const LEXICON_CORE: readonly string[] = [
  // Household / rooms / fixtures
  "toilet",
  "toilets",
  "bathroom",
  "restroom",
  "washroom",
  "lavatory",
  "kitchen",
  "kitchenette",
  "bedroom",
  "living",
  "room",
  "living room",
  "dining",
  "dining room",
  "garage",
  "basement",
  "attic",
  "hallway",
  "closet",
  "laundry",
  "porch",
  "patio",
  "deck",
  "yard",
  "garden",
  "fence",
  "door",
  "window",
  "stairs",
  "couch",
  "sofa",
  "chair",
  "table",
  "desk",
  "bed",
  "lamp",
  "mirror",
  "sink",
  "shower",
  "bathtub",
  "stove",
  "oven",
  "fridge",
  "refrigerator",
  "microwave",
  "dishwasher",
  "washer",
  "dryer",
  "vacuum",
  "broom",
  "trash",
  "bin",
  "towel",
  "pillow",
  "blanket",
  "curtain",
  "rug",
  "carpet",

  // Places / outdoors
  "beach",
  "shore",
  "ocean",
  "sea",
  "sand",
  "coast",
  "lake",
  "river",
  "mountain",
  "mountains",
  "forest",
  "woods",
  "park",
  "playground",
  "trail",
  "camp",
  "camping",
  "farm",
  "field",
  "meadow",
  "desert",
  "island",
  "waterfall",
  "pool",
  "swimming pool",
  "hot tub",
  "dock",
  "marina",
  "harbor",
  "city",
  "downtown",
  "street",
  "road",
  "bridge",
  "building",
  "office",
  "school",
  "church",
  "hospital",
  "store",
  "mall",
  "restaurant",
  "cafe",
  "hotel",
  "airport",
  "stadium",
  "museum",
  "zoo",
  "aquarium",
  "library",
  "gym",
  "indoor",
  "indoors",
  "outdoor",
  "outdoors",
  "inside",
  "outside",
  "interior",
  "exterior",
  "home",
  "house",
  "apartment",

  // Events / celebrations
  "wedding",
  "party",
  "birthday",
  "anniversary",
  "graduation",
  "funeral",
  "memorial",
  "holiday",
  "christmas",
  "thanksgiving",
  "halloween",
  "easter",
  "parade",
  "concert",
  "festival",
  "picnic",
  "barbecue",
  "bbq",
  "reunion",
  "ceremony",
  "reception",
  "shower",
  "baby shower",
  "bridal shower",
  "baptism",
  "christening",
  "prom",
  "dance",
  "celebration",
  "gathering",

  // Clothing / accessories
  "suit",
  "suits",
  "tuxedo",
  "tux",
  "tie",
  "ties",
  "necktie",
  "bow tie",
  "bowtie",
  "dress",
  "dresses",
  "gown",
  "formalwear",
  "jacket",
  "blazer",
  "coat",
  "sweater",
  "hoodie",
  "shirt",
  "blouse",
  "pants",
  "jeans",
  "shorts",
  "skirt",
  "hat",
  "cap",
  "scarf",
  "gloves",
  "boots",
  "shoes",
  "sneakers",
  "sandals",
  "socks",
  "uniform",
  "jersey",
  "costume",
  "pajamas",
  "swimsuit",
  "bikini",

  // Animals / pets
  "dog",
  "dogs",
  "puppy",
  "puppies",
  "cat",
  "cats",
  "kitten",
  "kittens",
  "bird",
  "birds",
  "horse",
  "horses",
  "pony",
  "fish",
  "rabbit",
  "bunny",
  "hamster",
  "pet",
  "pets",
  "cow",
  "cows",
  "pig",
  "pigs",
  "chicken",
  "chickens",
  "duck",
  "ducks",
  "deer",
  "bear",
  "lion",
  "tiger",
  "elephant",
  "monkey",
  "giraffe",
  "zebra",
  "canine",
  "feline",

  // Vehicles
  "car",
  "cars",
  "automobile",
  "vehicle",
  "truck",
  "trucks",
  "van",
  "suv",
  "motorcycle",
  "bike",
  "bicycle",
  "scooter",
  "bus",
  "train",
  "airplane",
  "plane",
  "jet",
  "helicopter",
  "boat",
  "boats",
  "ship",
  "canoe",
  "kayak",
  "sailboat",
  "yacht",
  "rv",
  "tractor",
  "ambulance",
  "firetruck",
  "taxi",

  // Food / drink
  "cake",
  "cupcake",
  "pie",
  "cookie",
  "cookies",
  "bread",
  "pizza",
  "burger",
  "sandwich",
  "salad",
  "soup",
  "pasta",
  "steak",
  "chicken",
  "turkey",
  "ham",
  "ice cream",
  "dessert",
  "candy",
  "chocolate",
  "coffee",
  "tea",
  "beer",
  "wine",
  "champagne",
  "juice",
  "water",
  "soda",
  "milk",
  "breakfast",
  "lunch",
  "dinner",
  "brunch",

  // Activities / props
  "cigar",
  "cigars",
  "cigarette",
  "cigarettes",
  "pipe",
  "smoking",
  "tobacco",
  "guitar",
  "piano",
  "violin",
  "drum",
  "drums",
  "ball",
  "soccer",
  "football",
  "basketball",
  "baseball",
  "tennis",
  "golf",
  "fishing",
  "hunting",
  "skiing",
  "snowboarding",
  "surfing",
  "swimming",
  "running",
  "hiking",
  "camping",
  "cooking",
  "baking",
  "gardening",
  "reading",
  "book",
  "books",
  "camera",
  "phone",
  "laptop",
  "computer",
  "tv",
  "television",
  "game",
  "toy",
  "toys",
  "balloon",
  "balloons",
  "gift",
  "gifts",
  "present",
  "presents",
  "flower",
  "flowers",
  "tree",
  "trees",
  "christmas tree",
  "candle",
  "candles",
  "firework",
  "fireworks",
  "flag",
  "umbrella",
  "backpack",
  "purse",
  "wallet",
  "keys",
  "watch",
  "jewelry",
  "necklace",
  "ring",
  "earring",

  // Party / inflatables
  "inflatable",
  "inflatables",
  "bounce",
  "bouncy",
  "bounce house",
  "bouncy castle",
  "obstacle",
  "obstacle course",
  "moonwalk",
  "slide",
  "swing",
  "jungle gym",

  // Media glue (never people)
  "photo",
  "photos",
  "picture",
  "pictures",
  "image",
  "images",
  "video",
  "videos",
  "selfie",
  "selfies",
  "portrait",
  "portraits",
  "snapshot",
  "slideshow",
  "movie",
  "montage",
  "album",
];

function singularizeLexeme(value: string): string {
  if (value.length > 3 && value.endsWith("ies")) {
    return `${value.slice(0, -3)}y`;
  }
  if (value.length > 3 && value.endsWith("s") && !value.endsWith("ss")) {
    return value.slice(0, -1);
  }
  return value;
}

function buildLexiconSet(): Set<string> {
  const out = new Set<string>();
  for (const term of LEXICON_CORE) {
    const lower = term.toLowerCase().trim();
    if (!lower) continue;
    out.add(lower);
    out.add(singularizeLexeme(lower));
  }
  for (const key of listVisualSynonymKeys()) {
    const lower = key.toLowerCase().trim();
    if (!lower) continue;
    out.add(lower);
    out.add(singularizeLexeme(lower));
  }
  return out;
}

let cachedLexicon: Set<string> | null = null;

/** Full common-object/scene lexicon (includes visual synonym keys). */
export function getCommonObjectSceneLexicon(): Set<string> {
  if (!cachedLexicon) cachedLexicon = buildLexiconSet();
  return cachedLexicon;
}

export function isCommonObjectOrSceneTerm(value: string): boolean {
  const lower = value.trim().toLowerCase();
  if (!lower) return false;
  const lexicon = getCommonObjectSceneLexicon();
  if (lexicon.has(lower)) return true;
  const stripped = lower.replace(/^(?:a|an|the)\s+/, "").trim();
  if (lexicon.has(stripped) || lexicon.has(singularizeLexeme(stripped))) {
    return true;
  }
  // Multi-word: any token in lexicon counts for phrases like "birthday cake photos"
  const tokens = stripped.split(/\s+/).filter((t) => t.length > 2);
  if (tokens.length > 1 && tokens.every((t) => lexicon.has(t) || lexicon.has(singularizeLexeme(t)))) {
    return true;
  }
  return tokens.some((t) => lexicon.has(t) && t.length >= 4);
}

/** Exposed for tests. */
export function listCommonObjectSceneTerms(): string[] {
  return [...getCommonObjectSceneLexicon()].sort();
}
